config/routes.rb
Rails.application.routes.draw do
 
  
  root :to => 'home#index'
  resources :home do
    collection do
      post 'import'
      post 'commaSeprtd'
      get 'exportCSV'
      get 'demoexportCSV'
      get 'zoneDropdownupdate'
      get 'updatePreview'
    end
  end
  mount ShopifyApp::Engine, at: '/'

end

app/models/home.rb
class Home < ActiveRecord::Base
  	belongs_to :shop 
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  require 'json'
  require 'csv'
  
  def index
    @session_data_all = ShopifyAPI::Shop.current
    curr_store_id = @session_data_all.id
    
    @compare_shop_id = Home.find_by_shopid(curr_store_id)
    @zip_zone_list = Zip.select(:zone).where(:shopid => curr_store_id).map(&:zone).uniq
    @zip_new_comm_sep = Zip.new
    if @compare_shop_id.nil?
    
      zipcontent = Zipcontent.find_by_zipcount(1)

      Home.create(:heading => zipcontent.heading,
                :shopid => curr_store_id,
                :avail_msg => zipcontent.avail_msg,
                :notavail_msg => zipcontent.notavail_msg,
                :success_txt_color => zipcontent.success_txt_color,
                :fail_txt_color => zipcontent.fail_txt_color,
                :btn_color => zipcontent.btn_color,
                :btn_font_color => zipcontent.btn_font_color,
                :heading_color => zipcontent.heading_color,
                :btn_border_color =>  zipcontent.btn_border_color
        )


      names = Array.new
      @zip_list = Zip.where(:shopid => curr_store_id)

      @zip_list.each do |zip_list|
        names << {"id": zip_list.id, "pincode": zip_list.pincode}
      end
      @zip_list_json = names.to_json


      ship_json_data = "var available_zip = "+@zip_list_json

      # create a snippet=======================================================
      @asset_snippet = ShopifyAPI::Asset.new(:key => 'snippets/ZipCode.liquid')
      @asset_snippet.value = '<div class="ship_calculator">'+
                              '<span><h2>'+zipcontent.heading+'</h2></span>'+
                              '<div class="ship_postal_srch">'+
                              '<input type="hidden" class="ship_total_weight"'+ 
                              'value="{{ cart.total_weight }}">'+
                              '<label>Postal Code:<span class="cart_imp">*</span></label>'+
                              '<input type="text" class="ship_postal_code">'+
                              '<span class="postal_error"></span>'+
                              '<a href="javascript:void(0);"'+ 
                              'class="btn shipping_status action_button">SUBMIT</a>'+
                              '<div class="add-product-loader">'+
                              '<img src="{{ "loader.gif" | asset_url }}"></div>'+
                              '</div></div>'+
                              '<div id="ship_target"></div><br class="clear" />'+
                              '<!-- =====================JS=========================='+
                              '================================================= -->'+
                              '<script>'+ship_json_data+'; $(".shipping_status").click(function(){'+
                             'var flag = 0;'+
                             '$(".add-product-loader").css("display","block");'+
                             'var cart_postal_code = $(".ship_postal_code").val();'+ 
                              'if(cart_postal_code !="")'+
                              '{'+
                                 '$.each(available_zip, function (key, code) {'+
                                   'if(cart_postal_code == code.pincode){'+
                                    'flag = 1;'+
                                   '}'+ 
                                 '});'+
                                'if(flag == 1){'+
                                  '$("#ship_target").empty();'+
                                  '$(".postal_error").empty();'+
                                  '$("#ship_target").html("'+zipcontent.avail_msg+'");'+
                                  '$(".add-product-loader").css("display","none");'+
                                '}'+
                                'else{'+
                                  '$("#ship_target").empty();'+
                                  '$(".postal_error").empty();'+
                                  '$("#ship_target").html("'+zipcontent.notavail_msg+'");'+
                                  '$(".add-product-loader").css("display","none");'+
                                '}'+
                              '}'+
                              'else{'+
                                '$("#ship_target").empty();'+
                                '$(".add-product-loader").css("display","none");'+
                                '$(".postal_error").text("*Postal code can not be blank.");'+
                              '}'+
                          '});</script>'+
                           '<!-- =====================CSS=========================='+
                           '================================================= -->'+
                           '<style>.add-product-loader {display: none;float: right;}'+
                           '.ship_calculator span h2{color:'+zipcontent.heading_color+' !important; }'+
                          '.ship_calculator{width:100%;}'+
                          '.ship_postal_srch{width:20%; }'+
                          '.cart_imp{color:red; }'+
                          '.ship_calculator input{padding:0 !important; margin:0 !important; }'+
                          '#ship_target {margin-top: 20px; color:'+zipcontent.success_txt_color+';}'+
                          '.postal_error{color:'+zipcontent.fail_txt_color+';font-weight: bold;}'+
                          '.btn.shipping_status.action_button {margin-top: 10px;width: 100%;border: 1px solid '+zipcontent.btn_border_color+' !important;background-color:'+zipcontent.btn_color+' !important;color:'+zipcontent.btn_font_color+'!important; }</style>'

      @asset_snippet.save
      # End here=========================================================

      # Add Snippet======================================================
      # @asset_edit = ShopifyAPI::Asset.find('templates/product.liquid')
      # @asset_edit.value += "<br><p>{% include 'ZipCode' %}</p>"
      # @asset_edit.save
      # End here=========================================================

      # Add Loader Image=================================================
      @asset_image = ShopifyAPI::Asset.new(:key => 'assets/loader.gif')
      @asset_image.src = 'https://cdn.shopify.com/s/files/1/1269/3465/files/loader.gif?5143915732747615527'
      @asset_image.save
      # End here=========================================================
    else 

      zipcontent = Home.find_by_shopid(curr_store_id)

      names = Array.new
      @zip_list = Zip.where(:shopid => curr_store_id)

      @zip_list.each do |zip_list|
        names << {"id": zip_list.id, "pincode": zip_list.pincode}
      end
      @zip_list_json = names.to_json


      ship_json_data = "var available_zip = "+@zip_list_json

      # create a snippet=======================================================
      @asset_snippet = ShopifyAPI::Asset.new(:key => 'snippets/ZipCode.liquid')
      @asset_snippet.value = '<div class="ship_calculator">'+
                              '<span><h2>'+zipcontent.heading+'</h2></span>'+
                              '<div class="ship_postal_srch">'+
                              '<input type="hidden" class="ship_total_weight"'+ 
                              'value="{{ cart.total_weight }}">'+
                              '<label>Postal Code:<span class="cart_imp">*</span></label>'+
                              '<input type="text" class="ship_postal_code">'+
                              '<span class="postal_error"></span>'+
                              '<a href="javascript:void(0);"'+ 
                              'class="btn shipping_status action_button">SUBMIT</a>'+
                              '<div class="add-product-loader">'+
                              '<img src="{{ "loader.gif" | asset_url }}"></div>'+
                              '</div></div>'+
                              '<div id="ship_target"></div><br class="clear" />'+
                              '<!-- =====================JS=========================='+
                              '================================================= -->'+
                              '<script>'+ship_json_data+'; $(".shipping_status").click(function(){'+
                             'var flag = 0;'+
                             '$(".add-product-loader").css("display","block");'+
                             'var cart_postal_code = $(".ship_postal_code").val();'+ 
                              'if(cart_postal_code !="")'+
                              '{'+
                                 '$.each(available_zip, function (key, code) {'+
                                   'if(cart_postal_code == code.pincode){'+
                                    'flag = 1;'+
                                   '}'+ 
                                 '});'+
                                'if(flag == 1){'+
                                  '$("#ship_target").empty();'+
                                  '$(".postal_error").empty();'+
                                  '$("#ship_target").html("'+zipcontent.avail_msg+'");'+
                                  '$(".add-product-loader").css("display","none");'+
                                '}'+
                                'else{'+
                                  '$("#ship_target").empty();'+
                                  '$(".postal_error").empty();'+
                                  '$("#ship_target").html("'+zipcontent.notavail_msg+'");'+
                                  '$(".add-product-loader").css("display","none");'+
                                '}'+
                              '}'+
                              'else{'+
                                '$("#ship_target").empty();'+
                                '$(".add-product-loader").css("display","none");'+
                                '$(".postal_error").text("*Postal code can not be blank.");'+
                              '}'+
                          '});</script>'+

app/views/home/_tabsetting.html.erb
 <div class="col-md-12 col-sm-12 blk-import">
    <div class="panel panel-default">
      <div class="panel-body">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#home" data-toggle="tab"><i class="fa fa-home dashboard-div-icon"></i> </a>
          </li>
          <li class=""><a href="#settings" data-toggle="tab"><i class="fa fa-cogs dashboard-div-icon"></i></a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane fade active in" id="home">
            <h4>Home Tab</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          </div>
          <div class="tab-pane fade" id="settings">
            <div class="panel-body">
              <ul class="nav nav-pills">
                <li class=""><a href="#home-pills" data-toggle="tab">Upload Settings</a>
                </li>
                <li class=""><a href="#profile-pills" data-toggle="tab">Appearance</a>
                </li>
                <li class=""><a href="#messages-pills" data-toggle="tab">Product Wise Shipping</a>
                </li>
              </ul>
              <div class="tab-content theme-setting">
                <div class="tab-pane fade" id="home-pills">
                  <div class="row">
                    <div class="col-sm-12 col-md-8">
                      <div class="panel-body">
                        <div class="panel-group" id="accordion">
                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" class="collapsed"> <i class="fa fa-plus-square" aria-hidden="true"></i> <i class="fa fa-minus-square" aria-hidden="true"></i> Bulk Import</a>
                              </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse" style="height: 0px;">
                              <div class="panel-body">
                                <div class="table-responsive">
                                 <%= form_tag import_home_index_path, class: "bulk_import", multipart: true, :remote => true do %>
                                    <table class="table table-striped">
                                      <tbody>
                                        <tr>
                                          <td>
                                              
                                              <div class='file_upload' id='f1'>
                                                <input type="textbox" id="f1" class="pin_zone_name" name="zone" placeholder="zone name">
                                                
                                                <input name='file[]' id='pincode_csv' type='file'/>
                                                
                                              </div>
                                              <!-- <div id='file_tools'>
                                                <img src='assets/plus.png' id='add_file' title='Add new input'/>
                                                <img src='assets/minus.jpg' id='del_file' title='Delete'/>
                                              </div> -->
                                              <input type='submit' name='upload' value='Upload'/>
                                           
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  <% end %>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" class="collapsed"> <i class="fa fa-plus-square" aria-hidden="true"></i> <i class="fa fa-minus-square" aria-hidden="true"></i> Manual Import</a>
                              </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse" style="height: auto;">
                              <div class="panel-body">
                                <div class="form-row">
                                  <%= form_for @zip_new_comm_sep, url: commaSeprtd_home_index_path, method: :post, :remote => true  do |f| %>
                                    <div class="pin_insert_comma_seperated">
                                      <%= f.select(:zone, @zip_zone_list, :prompt => 'Select Zone') %>
                                      <label>Enter Comma Seperated Pin:</label>
                                      <%= text_area :zip, :pincode %>

                                    </div>
                                    <span>Ex: 90001,311021,302028</span><br><br>
                                    
                                    <div class="new_pin_save">
                                      <%= submit_tag "Add" %>
                                    </div>
                                  <% end %>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree" class="collapsed"> <i class="fa fa-plus-square" aria-hidden="true"></i> <i class="fa fa-minus-square" aria-hidden="true"></i> Export</a>
                              </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse">
                              <div class="panel-body">
                                <div class="form-row">
                                  
                                  <%= form_tag exportCSV_home_index_path(format: :csv),  method: :get, class: "bulk_export", multipart: true do %>
                                    <div class="select_zone_for_export">
                                      <label>Select Zone (s)</label> 
                                      <%= select_tag(:zone, options_for_select(@zip_zone_list), :prompt => 'Select Zone') %>
                                    </div>
                                    <div class="zone_export">
                                      <%= submit_tag "Export", :class => 'zone_export_btn' %>
                                    </div>
                                  <% end %>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="tab-pane fade" id="profile-pills">
                  <div class="col-sm-12 col-md-8">
                    <h4><strong>Color / Font</strong></h4>
                    <div class="table-responsive">
                     
                      <%= form_for(@home, :remote => true) do |f| %>
                        <%= f.hidden_field :id %>
                        <table class="table table-striped">
                          <tbody>
                            <tr>
                              <td>Heading</td>
                              <td> Text </td>
                              <td >
                                 <%= f.text_field :heading, :id => 'ship_heading' %>
                              </td>
                            </tr>
                            <tr>
                              <td>Heading</td>
                              <td> Color </td>
                              <td >
                                <%= f.text_field :heading_color, :id => 'textbox5' %>
                              </td>
                            </tr>
                            <tr>
                              <td>Success Message</td>
                              <td> Color </td>
                              <td >
                                <%= f.text_field :success_txt_color, :id => 'textbox1' %>
                              </td>
                            </tr>
                            <tr>
                              <td>Unsuccessfull Message</td>
                              <td> Color </td>
                              <td >
                                <%= f.text_field :fail_txt_color, :id => 'textbox2'%>
                              </td>
                            </tr>
                            <tr>
                              <td>Button / Text</td>
                              <td> Color </td>
                              <td >
                                <%= f.text_field :btn_font_color, :id => 'textbox3' %>
                              </td>
                            </tr>
                            <tr>
                              <td>Button Background</td>
                              <td> Color </td>
                              <td >
                                <%= f.text_field :btn_color, :id => 'textbox4' %>
                              </td>
                            </tr>
                            <tr>
                              <td>Button Border</td>
                              <td> Color </td>
                              <td >
                                <%= f.text_field :btn_border_color, :id => 'textbox6' %>
                              </td>
                            </tr>
                            <tr>
                              <td>Shipping Available Message</td>
                              <td> Text </td>
                              <td >
                                <%= text_area :home, :avail_msg %>
                              </td>
                            </tr>
                             <tr>
                              <td>Shipping Not Available Message</td>
                              <td> Text </td>
                              <td >
                                <%= text_area :home, :notavail_msg %>
                              </td>
                            </tr>
                            <tr>
                              <td>
                                <div class="css_modified_content">
                                  <%= submit_tag "Update", :class => 'appearance_update' %>
                                </div>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      <% end %>
                    </div>
                  </div>
                  <div class="col-sm-12 col-md-4">
                    <h4><strong>Apperance</strong></h4>
                    <%= @curr_design.html_safe %>
                  </div>
                </div>
                <div class="tab-pane fade" id="messages-pills">
                  <h4>Product Wise Shipping</h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/home/demoexportCSV.html.erb
<%- @demopincodes.each do |pin| -%>
<%= CSV.generate_line([pin.pincode]) -%>
<%- end -%>

app/views/home/exportCSV.html.erb
<%- @pincodes.each do |pin| -%>
<%= CSV.generate_line([pin.pincode]) -%>
<%- end -%>